- name: clone dotfiles repositories
  git:
    repo: "{{ user_git_prefix }}{{ item.key }}.git"
    dest: "{{ getent_passwd[user][4] }}/{{ item.value }}"
    accept_hostkey: yes
  environment:
    SSH_AUTH_SOCK: "/run/user/{{ getent_passwd[user][2] }}/gnupg/S.gpg-agent.ssh"
    SSH_AGENT_PID: ""
  loop: "{{ user_repos | dict2items }}"

- name: password-store for gopass
  git:
    repo: "git@git.devops-now.com:shengis/pass.git"
    dest: "{{ getent_passwd[user][4] }}/.password-store"
    accept_hostkey: yes
  environment:
    SSH_AUTH_SOCK: "/run/user/{{ getent_passwd[user][2] }}/gnupg/S.gpg-agent.ssh"
    SSH_AGENT_PID: ""
