- include_vars: '{{ item }}'
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "../vars/{{ ansible_distribution }}.yaml"
    - "../vars/{{ ansible_os_family }}.yaml"
    - "../vars/default.yaml"

- import_tasks: ssh.yaml
- import_tasks: git.yaml
- import_tasks: yubikey.yaml
- import_tasks: dotfiles-repo.yaml
