- hosts: localhost
  connection: local

  pre_tasks:
    - name: test if user is root
      assert:
        that:
          - '{{ lookup("pipe", "id -u") == "0" }}'

  roles:
    - common
    - multimedia
    - gopass
