- name: get fedora version from rpm
  command: >
    rpm -E %fedora
  register: fedora_version

- name: install rpmfusion repository
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version.stdout }}.noarch.rpm

- name: install multimedia packages
  dnf:
    name:
      - ffmpeg
      - ffmpeg-libs
      - mpv
      - gimp
      - inkscape
