- include_vars: '{{ item }}'
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "../vars/{{ ansible_distribution }}.yaml"
    - "../vars/{{ ansible_os_family }}.yaml"
    - "../vars/default.yaml"

- name: update packages
  dnf:
    name: '*'
    state: latest

- name: install packages
  dnf:
    name: '{{ packages_name }}'
    state: present
