- include_vars: '{{ item }}'
  with_first_found:
    - "../vars/{{ ansible_distribution }}-{{ ansible_distribution_version }}.yaml"
    - "../vars/{{ ansible_distribution }}.yaml"
    - "../vars/{{ ansible_os_family }}.yaml"
    - "../vars/default.yaml"

- name: create temp directory
  tempfile:
    state: directory
  register: temp_dir

- name: get latest release from github
  uri:
    url: https://api.github.com/repos/{{ kitty_repo }}/releases/latest
  register: latest_release

- name: unarchive kitty
  unarchive:
    src: "{{ (latest_release.json.assets | selectattr('name', 'search', kitty_file_suffix+'$') | map(attribute='browser_download_url') | list)[0] }}"
    dest: "{{ temp_dir.path }}"
    remote_src: yes

- name: fix permissions
  shell: >
    find {{ temp_dir.path }} -type f -perm 0766 -exec chmod 0755 \{\} \;

- name: copy extracted archive to /usr/local/bin
  copy:
    src: "{{ temp_dir.path }}/"
    dest: /usr/local/
    owner: root
    group: root

- name: remove temporary directory
  file:
    path: "{{ temp_dir.path }}"
    state: absent
